# docker-compose.yml
vendors:
  image: python:3
  working_dir: /mnt
  volumes:
    - ../:/mnt
  environment:
    PYTHONUSERBASE: /mnt/vendor
  command: pip install -r requirements.txt --user --upgrade

server:
  image: python:3
  working_dir: /mnt
  volumes:
    - ../:/mnt
  ports:
    - '8080:8080'
  environment:
    PYTHONPATH: src
    PYTHONUSERBASE: /mnt/vendor
  command: python -u omush/server.py

client:
  image: python:3
  working_dir: /mnt
  volumes:
    - ../:/mnt
  environment:
    PYTHONPATH: src
    PYTHONUSERBASE: /mnt/vendor
  command: python client.py ws://server:9000 debug
  links:
    - server

test:
  image: python:3
  working_dir: /mnt
  volumes:
    - ../:/mnt
  environment:
    PYTHONPATH: src
    PYTHONUSERBASE: /mnt/vendor
  command: bash -c "pip install nose  && nosetests"
